use customer_behaviour;
select * from customer limit 5;

-- Q1. What is the total Revenue generated by male VS female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(AVG(review_rating),2) as 'Avg Product Rating'
FROM customer 
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard ans Express Shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount), 2)
from customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribed?
SELECT subscription_status, 
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC ;

-- Q6. Which 5 products have the highest percentage of purchases whith discounts applied?
SELECT item_purchased,
ROUND(COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100 /COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer
)
SELECT customer_segment, COUNT(*) AS 'No of Cust'
from customer_type
GROUP BY customer_segment;

-- Q8. what are the Top 3 most purchased products withi each category?
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
from customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 SELECT subscription_status, 
 count(customer_id) as repeat_buyers
 FROM customer
 WHERE previous_purchases > 5
 GROUP BY subscription_status;
 
 -- Q10. What is the revenue contribition of each age group?
SELECT age_group,
SUM(purchase_amount) as revenue
FROM customer
GROUP BY age_group
ORDER BY revenue desc; 